-- Auto-generated from runs/v2-007/validation.json top3_confusions_per_sign.
-- 120 pairs. Authored mechanically from ASL-LEX 2.0 phonological
-- features (handshape, location, movement) per ADR 0004 slice-1 methodology.
-- Slice-2 plan: paid Deaf-signer review per ADR 0004; this seed is the placeholder.

truncate table public.confusion_pair_hints;

insert into public.confusion_pair_hints (target_sign_id, predicted_sign_id, hint) values
  ('milk', 'yellow', 'Looks like you signed "yellow" instead of "milk". They differ in handshape (s vs y) and selected fingers (imrp vs p). Watch the reference to feel the difference.'),
  ('pizza', 'no', 'Looks like you signed "no" instead of "pizza". They differ in handshape (l vs flat_h) and selected fingers (i vs im). Watch the reference to feel the difference.'),
  ('who', 'sorry', 'Looks like you signed "sorry" instead of "who". They differ in sign location (Head vs Body) and handshape (l vs a). Watch the reference to feel the difference.'),
  ('milk', 'cold', 'Looks like you signed "cold" instead of "milk". They differ in sign location (Neutral vs Body) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('black', 'drink', 'Looks like you signed "drink" instead of "black". They differ in handshape (1 vs c) and specific location (Forehead vs HeadAway). Watch the reference to feel the difference.'),
  ('pizza', 'car', 'Looks like you signed "car" instead of "pizza". They differ in handshape (l vs s) and movement (None vs Curved). Watch the reference to feel the difference.'),
  ('go', 'people', 'Looks like you signed "people" instead of "go". They differ in handshape (1 vs p) and movement (Curved vs Circular). Watch the reference to feel the difference.'),
  ('cat', 'home', 'Looks like you signed "home" instead of "cat". They differ in handshape (f vs o) and specific location (CheekNose vs Chin). Watch the reference to feel the difference.'),
  ('apple', 'bird', 'Looks like you signed "bird" instead of "apple". They differ in handshape (bent_1 vs g) and specific location (CheekNose vs Mouth). Watch the reference to feel the difference.'),
  ('good', 'baby', 'Looks like you signed "baby" instead of "good". They differ in sign location (Head vs Neutral) and specific location (Chin vs Neutral). Watch the reference to feel the difference.'),
  ('brother', 'sister', 'Looks like you signed "sister" instead of "brother". They differ in handshape (a vs l) and specific location (Forehead vs CheekNose). Watch the reference to feel the difference.'),
  ('dog', 'cat', 'Looks like you signed "cat" instead of "dog". They differ in sign location (Neutral vs Head) and handshape (d vs f). Watch the reference to feel the difference.'),
  ('want', 'sad', 'Looks like you signed "sad" instead of "want". They differ in sign location (Neutral vs Head) and specific location (Neutral vs HeadAway). Watch the reference to feel the difference.'),
  ('baby', 'my', 'Looks like you signed "my" instead of "baby". They differ in sign location (Neutral vs Body) and specific location (Neutral vs TorsoTop). Watch the reference to feel the difference.'),
  ('milk', 'feel', 'Looks like you signed "feel" instead of "milk". They differ in sign location (Neutral vs Body) and handshape (s vs open_8). Watch the reference to feel the difference.'),
  ('black', 'apple', 'Looks like you signed "apple" instead of "black". They differ in handshape (1 vs bent_1) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('black', 'bird', 'Looks like you signed "bird" instead of "black". They differ in handshape (1 vs g) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('fish', 'school', 'Looks like you signed "school" instead of "fish". They differ in handshape (open_b vs 5) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('fish', 'help', 'Looks like you signed "help" instead of "fish". They differ in handshape (open_b vs a) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('fish', 'white', 'Looks like you signed "white" instead of "fish". They differ in sign location (Hand vs Body) and handshape (open_b vs flatspread_5). Watch the reference to feel the difference.'),
  ('pizza', 'white', 'Looks like you signed "white" instead of "pizza". They differ in sign location (Neutral vs Body) and handshape (l vs flatspread_5). Watch the reference to feel the difference.'),
  ('feel', 'learn', 'Looks like you signed "learn" instead of "feel". They differ in sign location (Body vs Hand) and handshape (open_8 vs flatspread_5). Watch the reference to feel the difference.'),
  ('feel', 'red', 'Looks like you signed "red" instead of "feel". They differ in sign location (Body vs Head) and handshape (open_8 vs 1). Watch the reference to feel the difference.'),
  ('feel', 'my', 'Looks like you signed "my" instead of "feel". They differ in handshape (open_8 vs open_b) and movement (Curved vs Straight). Watch the reference to feel the difference.'),
  ('go', 'deaf', 'Looks like you signed "deaf" instead of "go". They differ in sign location (Neutral vs Head) and specific location (Neutral vs Other). Watch the reference to feel the difference.'),
  ('go', 'cat', 'Looks like you signed "cat" instead of "go". They differ in sign location (Neutral vs Head) and handshape (1 vs f). Watch the reference to feel the difference.'),
  ('green', 'yellow', 'Looks like you signed "yellow" instead of "green". They differ in handshape (g vs y) and selected fingers (i vs p). Watch the reference to feel the difference.'),
  ('green', 'no', 'Looks like you signed "no" instead of "green". They differ in handshape (g vs flat_h) and selected fingers (i vs im). Watch the reference to feel the difference.'),
  ('green', 'understand', 'Looks like you signed "understand" instead of "green". They differ in sign location (Neutral vs Head) and handshape (g vs baby_o). Watch the reference to feel the difference.'),
  ('house', 'teacher', 'Looks like you signed "teacher" instead of "house". They differ in sign location (Neutral vs Head) and handshape (flat_b vs o). Watch the reference to feel the difference.'),
  ('house', 'black', 'Looks like you signed "black" instead of "house". They differ in sign location (Neutral vs Head) and handshape (flat_b vs 1). Watch the reference to feel the difference.'),
  ('house', 'no', 'Looks like you signed "no" instead of "house". They differ in handshape (flat_b vs flat_h) and movement (Curved vs None). Watch the reference to feel the difference.'),
  ('sign', 'milk', 'Looks like you signed "milk" instead of "sign". They differ in handshape (1 vs s) and movement (Circular vs None). Watch the reference to feel the difference.'),
  ('sign', 'people', 'Looks like you signed "people" instead of "sign". They differ in handshape (1 vs p) and selected fingers (i vs im). Watch the reference to feel the difference.'),
  ('sign', 'friend', 'Looks like you signed "friend" instead of "sign". They differ in handshape (1 vs curved_1) and movement (Circular vs Other). Watch the reference to feel the difference.'),
  ('car', 'live', 'Looks like you signed "live" instead of "car". They differ in sign location (Neutral vs Body) and handshape (s vs l). Watch the reference to feel the difference.'),
  ('car', 'angry', 'Looks like you signed "angry" instead of "car". They differ in sign location (Neutral vs Body) and handshape (s vs 5). Watch the reference to feel the difference.'),
  ('car', 'hurt', 'Looks like you signed "hurt" instead of "car". They differ in handshape (s vs 1) and movement (Curved vs Circular). Watch the reference to feel the difference.'),
  ('cat', 'man', 'Looks like you signed "man" instead of "cat". They differ in handshape (f vs 5) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('cat', 'yesterday', 'Looks like you signed "yesterday" instead of "cat". They differ in handshape (f vs a) and movement (Straight vs Curved). Watch the reference to feel the difference.'),
  ('sorry', 'red', 'Looks like you signed "red" instead of "sorry". They differ in sign location (Body vs Head) and handshape (a vs 1). Watch the reference to feel the difference.'),
  ('sorry', 'hot', 'Looks like you signed "hot" instead of "sorry". They differ in sign location (Body vs Head) and handshape (a vs flatspread_5). Watch the reference to feel the difference.'),
  ('sorry', 'white', 'Looks like you signed "white" instead of "sorry". They differ in handshape (a vs flatspread_5) and movement (Circular vs Straight). Watch the reference to feel the difference.'),
  ('tomorrow', 'fish', 'Looks like you signed "fish" instead of "tomorrow". They differ in sign location (Head vs Hand) and handshape (a vs open_b). Watch the reference to feel the difference.'),
  ('tomorrow', 'who', 'Looks like you signed "who" instead of "tomorrow". They differ in handshape (a vs l) and movement (Curved vs None). Watch the reference to feel the difference.'),
  ('tomorrow', 'bathroom', 'Looks like you signed "bathroom" instead of "tomorrow". They differ in sign location (Head vs Neutral) and handshape (a vs t). Watch the reference to feel the difference.'),
  ('apple', 'deaf', 'Looks like you signed "deaf" instead of "apple". They differ in handshape (bent_1 vs 1) and movement (None vs Curved). Watch the reference to feel the difference.'),
  ('fine', 'your', 'Looks like you signed "your" instead of "fine". They differ in sign location (Body vs Neutral) and specific location (TorsoTop vs Neutral). Watch the reference to feel the difference.'),
  ('fine', 'mom', 'Looks like you signed "mom" instead of "fine". They differ in sign location (Body vs Head) and specific location (TorsoTop vs Chin). Watch the reference to feel the difference.'),
  ('fine', 'go', 'Looks like you signed "go" instead of "fine". They differ in sign location (Body vs Neutral) and handshape (5 vs 1). Watch the reference to feel the difference.'),
  ('good', 'black', 'Looks like you signed "black" instead of "good". They differ in handshape (open_b vs 1) and specific location (Chin vs Forehead). Watch the reference to feel the difference.'),
  ('night', 'school', 'Looks like you signed "school" instead of "night". They differ in handshape (flat_b vs 5) and specific location (PalmBack vs Palm). Watch the reference to feel the difference.'),
  ('night', 'fish', 'Looks like you signed "fish" instead of "night". They differ in handshape (flat_b vs open_b) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('night', 'work', 'Looks like you signed "work" instead of "night". They differ in handshape (flat_b vs s) and flexion (Flat vs FullyClosed). Watch the reference to feel the difference.'),
  ('school', 'nice', 'Looks like you signed "nice" instead of "school". They differ in handshape (5 vs open_b) and repetition (1 vs 0). Watch the reference to feel the difference.'),
  ('school', 'day', 'Looks like you signed "day" instead of "school". They differ in sign location (Hand vs Neutral) and handshape (5 vs 1). Watch the reference to feel the difference.'),
  ('school', 'morning', 'Looks like you signed "morning" instead of "school". They differ in sign location (Hand vs Neutral) and handshape (5 vs open_b). Watch the reference to feel the difference.'),
  ('brother', 'night', 'Looks like you signed "night" instead of "brother". They differ in sign location (Head vs Hand) and handshape (a vs flat_b). Watch the reference to feel the difference.'),
  ('mom', 'who', 'Looks like you signed "who" instead of "mom". They differ in handshape (5 vs l) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('mom', 'no', 'Looks like you signed "no" instead of "mom". They differ in sign location (Head vs Neutral) and handshape (5 vs flat_h). Watch the reference to feel the difference.'),
  ('mom', 'school', 'Looks like you signed "school" instead of "mom". They differ in sign location (Head vs Hand) and specific location (Chin vs Palm). Watch the reference to feel the difference.'),
  ('white', 'hot', 'Looks like you signed "hot" instead of "white". They differ in sign location (Body vs Head) and movement (Straight vs Curved). Watch the reference to feel the difference.'),
  ('white', 'sorry', 'Looks like you signed "sorry" instead of "white". They differ in handshape (flatspread_5 vs a) and movement (Straight vs Circular). Watch the reference to feel the difference.'),
  ('white', 'my', 'Looks like you signed "my" instead of "white". They differ in handshape (flatspread_5 vs open_b) and flexion (Flat vs FullyOpen). Watch the reference to feel the difference.'),
  ('again', 'dog', 'Looks like you signed "dog" instead of "again". They differ in sign location (Hand vs Neutral) and handshape (flat_b vs d). Watch the reference to feel the difference.'),
  ('again', 'small', 'Looks like you signed "small" instead of "again". They differ in sign location (Hand vs Neutral) and handshape (flat_b vs c). Watch the reference to feel the difference.'),
  ('bathroom', 'no', 'Looks like you signed "no" instead of "bathroom". They differ in handshape (t vs flat_h) and selected fingers (i vs im). Watch the reference to feel the difference.'),
  ('bathroom', 'tomorrow', 'Looks like you signed "tomorrow" instead of "bathroom". They differ in sign location (Neutral vs Head) and handshape (t vs a). Watch the reference to feel the difference.'),
  ('have', 'again', 'Looks like you signed "again" instead of "have". They differ in sign location (Body vs Hand) and movement (Straight vs Curved). Watch the reference to feel the difference.'),
  ('have', 'car', 'Looks like you signed "car" instead of "have". They differ in sign location (Body vs Neutral) and handshape (flat_b vs s). Watch the reference to feel the difference.'),
  ('how', 'live', 'Looks like you signed "live" instead of "how". They differ in sign location (Neutral vs Body) and handshape (c vs l). Watch the reference to feel the difference.'),
  ('how', 'friend', 'Looks like you signed "friend" instead of "how". They differ in handshape (c vs curved_1) and movement (Curved vs Other). Watch the reference to feel the difference.'),
  ('how', 'name', 'Looks like you signed "name" instead of "how". They differ in sign location (Neutral vs Hand) and handshape (c vs h). Watch the reference to feel the difference.'),
  ('meet', 'deaf', 'Looks like you signed "deaf" instead of "meet". They differ in sign location (Neutral vs Head) and movement (Straight vs Curved). Watch the reference to feel the difference.'),
  ('meet', 'cold', 'Looks like you signed "cold" instead of "meet". They differ in sign location (Neutral vs Body) and handshape (1 vs s). Watch the reference to feel the difference.'),
  ('need', 'bathroom', 'Looks like you signed "bathroom" instead of "need". They differ in handshape (bent_1 vs t) and movement (Curved vs None). Watch the reference to feel the difference.'),
  ('need', 'no', 'Looks like you signed "no" instead of "need". They differ in handshape (bent_1 vs flat_h) and movement (Curved vs None). Watch the reference to feel the difference.'),
  ('nice', 'student', 'Looks like you signed "student" instead of "nice". They differ in handshape (open_b vs flatspread_5) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('nice', 'school', 'Looks like you signed "school" instead of "nice". They differ in handshape (open_b vs 5) and repetition (0 vs 1). Watch the reference to feel the difference.'),
  ('red', 'eat', 'Looks like you signed "eat" instead of "red". They differ in handshape (1 vs o) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('red', 'who', 'Looks like you signed "who" instead of "red". They differ in handshape (1 vs l) and specific location (Mouth vs Chin). Watch the reference to feel the difference.'),
  ('week', 'night', 'Looks like you signed "night" instead of "week". They differ in handshape (1 vs flat_b) and specific location (Palm vs PalmBack). Watch the reference to feel the difference.'),
  ('week', 'nice', 'Looks like you signed "nice" instead of "week". They differ in handshape (1 vs open_b) and selected fingers (i vs imrp). Watch the reference to feel the difference.'),
  ('yellow', 'dog', 'Looks like you signed "dog" instead of "yellow". They differ in handshape (y vs d) and selected fingers (p vs mrp). Watch the reference to feel the difference.'),
  ('yellow', 'understand', 'Looks like you signed "understand" instead of "yellow". They differ in sign location (Neutral vs Head) and handshape (y vs baby_o). Watch the reference to feel the difference.'),
  ('deaf', 'mom', 'Looks like you signed "mom" instead of "deaf". They differ in handshape (1 vs 5) and movement (Curved vs Straight). Watch the reference to feel the difference.'),
  ('deaf', 'bird', 'Looks like you signed "bird" instead of "deaf". They differ in handshape (1 vs g) and movement (Curved vs None). Watch the reference to feel the difference.'),
  ('deaf', 'no', 'Looks like you signed "no" instead of "deaf". They differ in sign location (Head vs Neutral) and handshape (1 vs flat_h). Watch the reference to feel the difference.'),
  ('dog', 'feel', 'Looks like you signed "feel" instead of "dog". They differ in sign location (Neutral vs Body) and handshape (d vs open_8). Watch the reference to feel the difference.'),
  ('dog', 'yellow', 'Looks like you signed "yellow" instead of "dog". They differ in handshape (d vs y) and selected fingers (mrp vs p). Watch the reference to feel the difference.'),
  ('cold', 'how', 'Looks like you signed "how" instead of "cold". They differ in sign location (Body vs Neutral) and handshape (s vs c). Watch the reference to feel the difference.'),
  ('cold', 'cat', 'Looks like you signed "cat" instead of "cold". They differ in sign location (Body vs Head) and handshape (s vs f). Watch the reference to feel the difference.'),
  ('play', 'cold', 'Looks like you signed "cold" instead of "play". They differ in sign location (Neutral vs Body) and handshape (y vs s). Watch the reference to feel the difference.'),
  ('play', 'have', 'Looks like you signed "have" instead of "play". They differ in sign location (Neutral vs Body) and handshape (y vs flat_b). Watch the reference to feel the difference.'),
  ('think', 'understand', 'Looks like you signed "understand" instead of "think". They differ in handshape (flat_1 vs baby_o) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('think', 'apple', 'Looks like you signed "apple" instead of "think". They differ in handshape (flat_1 vs bent_1) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('yesterday', 'pizza', 'Looks like you signed "pizza" instead of "yesterday". They differ in sign location (Head vs Neutral) and handshape (a vs l). Watch the reference to feel the difference.'),
  ('yesterday', 'no', 'Looks like you signed "no" instead of "yesterday". They differ in sign location (Head vs Neutral) and handshape (a vs flat_h). Watch the reference to feel the difference.'),
  ('want', 'book', 'Looks like you signed "book" instead of "want". They differ in handshape (5 vs open_b) and movement (Straight vs Curved). Watch the reference to feel the difference.'),
  ('no', 'bathroom', 'Looks like you signed "bathroom" instead of "no". They differ in handshape (flat_h vs t) and selected fingers (im vs i). Watch the reference to feel the difference.'),
  ('no', 'computer', 'Looks like you signed "computer" instead of "no". They differ in handshape (flat_h vs open_8) and movement (None vs Circular). Watch the reference to feel the difference.'),
  ('eat', 'good', 'Looks like you signed "good" instead of "eat". They differ in handshape (o vs open_b) and specific location (Mouth vs Chin). Watch the reference to feel the difference.'),
  ('eat', 'red', 'Looks like you signed "red" instead of "eat". They differ in handshape (o vs 1) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('grandma', 'school', 'Looks like you signed "school" instead of "grandma". They differ in sign location (Head vs Hand) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('hurt', 'have', 'Looks like you signed "have" instead of "hurt". They differ in sign location (Neutral vs Body) and handshape (1 vs flat_b). Watch the reference to feel the difference.'),
  ('live', 'play', 'Looks like you signed "play" instead of "live". They differ in sign location (Body vs Neutral) and handshape (l vs y). Watch the reference to feel the difference.'),
  ('live', 'cold', 'Looks like you signed "cold" instead of "live". They differ in handshape (l vs s) and movement (Curved vs Straight). Watch the reference to feel the difference.'),
  ('understand', 'think', 'Looks like you signed "think" instead of "understand". They differ in handshape (baby_o vs flat_1) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('your', 'grandma', 'Looks like you signed "grandma" instead of "your". They differ in sign location (Neutral vs Head) and movement (Straight vs None). Watch the reference to feel the difference.'),
  ('angry', 'live', 'Looks like you signed "live" instead of "angry". They differ in handshape (5 vs l) and specific location (TorsoTop vs TorsoBottom). Watch the reference to feel the difference.'),
  ('family', 'learn', 'Looks like you signed "learn" instead of "family". They differ in sign location (Neutral vs Hand) and handshape (f vs flatspread_5). Watch the reference to feel the difference.'),
  ('friend', 'deaf', 'Looks like you signed "deaf" instead of "friend". They differ in sign location (Neutral vs Head) and handshape (curved_1 vs 1). Watch the reference to feel the difference.'),
  ('hearing', 'pizza', 'Looks like you signed "pizza" instead of "hearing". They differ in sign location (Head vs Neutral) and handshape (1 vs l). Watch the reference to feel the difference.'),
  ('learn', 'drink', 'Looks like you signed "drink" instead of "learn". They differ in sign location (Hand vs Head) and handshape (flatspread_5 vs c). Watch the reference to feel the difference.'),
  ('man', 'water', 'Looks like you signed "water" instead of "man". They differ in handshape (5 vs w) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('sister', 'brother', 'Looks like you signed "brother" instead of "sister". They differ in handshape (l vs a) and specific location (CheekNose vs Forehead). Watch the reference to feel the difference.'),
  ('student', 'week', 'Looks like you signed "week" instead of "student". They differ in handshape (flatspread_5 vs 1) and movement (None vs Straight). Watch the reference to feel the difference.'),
  ('teacher', 'cat', 'Looks like you signed "cat" instead of "teacher". They differ in handshape (o vs f) and specific location (HeadAway vs CheekNose). Watch the reference to feel the difference.'),
  ('water', 'fine', 'Looks like you signed "fine" instead of "water". They differ in sign location (Head vs Body) and handshape (w vs 5). Watch the reference to feel the difference.'),
  ('work', 'night', 'Looks like you signed "night" instead of "work". They differ in handshape (s vs flat_b) and flexion (FullyClosed vs Flat). Watch the reference to feel the difference.')
;