-- Align the practice sidebar (vocabulary_items) to the TRAINING vocab
-- (dataset/sem_lex_top80_vocabulary.json — the 80 top-sem_lex words).
--
-- WHY .draft / NOT auto-applied: 55 of these 80 signs are NEW to the DB
-- (old table = slice1b: again/mom/dad/know/...). Activating them WITHOUT
-- reference videos + avatar templates would surface words whose practice
-- screen is broken. Apply ONLY after those assets exist:
--   * avatar templates  -> public/templates/<sign>.json  (DONE: medoid export)
--   * reference videos   -> 20260524010000_seed_reference_videos_top80.sql
-- Recognition is unaffected: all model_versions rows are deactivated
-- (20260520200000), so the runner uses stubPredict() for every sign.
-- Sidebar order = sem_lex clip count desc (most-trained first). Categories
-- are semantic (see prettyCategory / CATEGORY_LABELS in sidebar.tsx).
--
-- Apply: mv ...sql.draft ...sql && supabase db push  (or run in SQL editor)

-- 1) deactivate everything, then (2) upsert+activate the 80 training signs.
update public.vocabulary_items set is_active_for_practice = false;


insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('eat', 'EAT', 'food', 'movement', false, 1, true, 597) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('water', 'WATER', 'food', 'movement', false, 2, true, 408) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('money', 'MONEY', 'things', 'movement', false, 3, true, 335) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('animal', 'ANIMAL', 'animals', 'movement', false, 4, true, 328) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('clothes', 'CLOTHES', 'things', 'movement', false, 5, true, 312) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('work', 'WORK', 'verbs-common', 'movement', false, 6, true, 307) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('clean', 'CLEAN', 'descriptors', 'movement', false, 7, true, 284) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('car', 'CAR', 'things', 'movement', false, 8, true, 279) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('time', 'TIME', 'things', 'movement', false, 9, true, 271) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('finish', 'FINISH', 'verbs-common', 'movement', false, 10, true, 251) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('hurt', 'HURT', 'body-health', 'movement', false, 11, true, 248) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('school', 'SCHOOL', 'things', 'movement', false, 12, true, 237) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('pretty', 'PRETTY', 'descriptors', 'movement', false, 13, true, 236) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('cold', 'COLD', 'descriptors', 'movement', false, 14, true, 229) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('fun', 'FUN', 'feelings', 'movement', false, 15, true, 225) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('big', 'BIG', 'descriptors', 'movement', false, 16, true, 224) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('numbers', 'NUMBERS', 'things', 'movement', false, 17, true, 222) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('cool', 'COOL', 'descriptors', 'movement', false, 18, true, 221) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('drink', 'DRINK', 'food', 'movement', false, 19, true, 216) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('warm', 'WARM', 'descriptors', 'movement', false, 20, true, 212) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('color', 'COLOR', 'descriptors', 'movement', false, 21, true, 212) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('music', 'MUSIC', 'things', 'movement', false, 22, true, 212) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('sleep', 'SLEEP', 'verbs-common', 'movement', false, 23, true, 211) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('hot', 'HOT', 'descriptors', 'movement', false, 24, true, 208) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('sick', 'SICK', 'feelings', 'movement', false, 25, true, 207) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('hair', 'HAIR', 'body-health', 'movement', false, 26, true, 202) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('family', 'FAMILY', 'people', 'movement', false, 27, true, 200) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('baby', 'BABY', 'people', 'movement', false, 28, true, 199) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('play', 'PLAY', 'verbs-common', 'movement', false, 29, true, 192) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('sad', 'SAD', 'feelings', 'movement', false, 30, true, 191) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('delicious', 'DELICIOUS', 'food', 'movement', false, 31, true, 186) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('fruit', 'FRUIT', 'food', 'movement', false, 32, true, 186) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('learn', 'LEARN', 'verbs-common', 'movement', false, 33, true, 181) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('people', 'PEOPLE', 'people', 'movement', false, 34, true, 178) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('dirty', 'DIRTY', 'descriptors', 'movement', false, 35, true, 166) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('sweet', 'SWEET', 'food', 'movement', false, 36, true, 166) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('happy', 'HAPPY', 'feelings', 'movement', false, 37, true, 165) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('nice', 'NICE', 'feelings', 'movement', false, 38, true, 165) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('enjoy', 'ENJOY', 'feelings', 'movement', false, 39, true, 163) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('different', 'DIFFERENT', 'descriptors', 'movement', false, 40, true, 159) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('snow', 'SNOW', 'nature', 'movement', false, 41, true, 157) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('ball', 'BALL', 'things', 'movement', false, 42, true, 156) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('paper', 'PAPER', 'things', 'movement', false, 43, true, 152) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('sports', 'SPORTS', 'things', 'movement', false, 44, true, 152) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('game', 'GAME', 'things', 'movement', false, 45, true, 150) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('tired', 'TIRED', 'feelings', 'movement', false, 46, true, 149) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('red', 'RED', 'descriptors', 'movement', false, 47, true, 148) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('write', 'WRITE', 'verbs-common', 'movement', false, 48, true, 146) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('vegetable', 'VEGETABLE', 'food', 'movement', false, 49, true, 146) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('old', 'OLD', 'descriptors', 'movement', false, 50, true, 144) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('dog', 'DOG', 'animals', 'movement', false, 51, true, 144) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('bird', 'BIRD', 'animals', 'movement', false, 52, true, 141) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('rain', 'RAIN', 'nature', 'movement', false, 53, true, 141) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('kid', 'KID', 'people', 'movement', false, 54, true, 140) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('scared', 'SCARED', 'feelings', 'movement', false, 55, true, 140) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('dark', 'DARK', 'descriptors', 'movement', false, 56, true, 138) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('friend', 'FRIEND', 'people', 'movement', false, 57, true, 138) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('good', 'GOOD', 'descriptors', 'movement', false, 58, true, 137) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('help', 'HELP', 'verbs-common', 'movement', false, 59, true, 136) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('love', 'LOVE', 'feelings', 'movement', false, 60, true, 135) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('understand', 'UNDERSTAND', 'verbs-common', 'movement', false, 61, true, 133) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('house', 'HOUSE', 'things', 'movement', false, 62, true, 132) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('body', 'BODY', 'body-health', 'movement', false, 63, true, 132) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('nothing', 'NOTHING', 'misc', 'movement', false, 64, true, 131) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('see', 'SEE', 'verbs-common', 'movement', false, 65, true, 131) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('doctor', 'DOCTOR', 'people', 'movement', false, 66, true, 130) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('where', 'WHERE', 'misc', 'movement', false, 67, true, 130) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('swim', 'SWIM', 'verbs-common', 'movement', false, 68, true, 129) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('same', 'SAME', 'descriptors', 'movement', false, 69, true, 129) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('health', 'HEALTH', 'body-health', 'movement', false, 70, true, 129) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('read', 'READ', 'verbs-common', 'movement', false, 71, true, 128) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('tree', 'TREE', 'nature', 'movement', false, 72, true, 128) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('building', 'BUILDING', 'things', 'movement', false, 73, true, 127) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('sun', 'SUN', 'nature', 'movement', false, 74, true, 127) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('safe', 'SAFE', 'misc', 'movement', false, 75, true, 125) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('remember', 'REMEMBER', 'verbs-common', 'movement', false, 76, true, 125) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('wait', 'WAIT', 'verbs-common', 'movement', false, 77, true, 125) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('feel', 'FEEL', 'feelings', 'movement', false, 78, true, 123) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('flower', 'FLOWER', 'nature', 'movement', false, 79, true, 122) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;
insert into public.vocabulary_items (id, display_gloss, category, static_or_movement, flippable, difficulty_rank, is_active_for_practice, wlasl_clip_count) values ('follow', 'FOLLOW', 'verbs-common', 'movement', false, 80, true, 121) on conflict (id) do update set is_active_for_practice = true, difficulty_rank = excluded.difficulty_rank, display_gloss = excluded.display_gloss, category = excluded.category;

-- 3) The 10 signs without a mocap avatar yet → "Pending" category. The sidebar
-- (components/practice/sidebar.tsx) renders the "pending" category LAST and
-- labels it "Pending — avatar coming soon". They stay active for practice
-- (recognition is stubPredict) but visually flag that the avatar is in progress.
update public.vocabulary_items set category = 'pending'
where id in ('eat','time','numbers','sports','cool','dark','sick','baby','follow','nothing');
