-- Failure-production hints (generic_failure_hint) for the 80 active signs.
-- Generated by scripts/gen_failure_hints.py from ASL-LEX 2.0 phonology
-- (training/data/sources/asl_lex_signdata.csv, Sevcikova Sehyr et al. 2021),
-- joined via the seed asl_lex_code mapping (20260519100200_seed_vocabulary.sql).
-- Each hint names the actual handshape + location + movement so the fail screen
-- can show a concrete 'how to sign it' tip. Idempotent: re-run safe (UPDATE in place).
-- Sign ids without an ASL-LEX match fall back to a safe generic 3-step copy (none today).

update public.vocabulary_items set generic_failure_hint = 'To sign ANIMAL: Use both hands in a flat ''B'' (flat hand, fingers together), mirrored. Position it high on your chest and move it in a straight line, repeating the motion.' where id = 'animal';
update public.vocabulary_items set generic_failure_hint = 'To sign BABY: Use both hands in an open ''B'' (flat hand, fingers spread a little), mirrored. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'baby';
update public.vocabulary_items set generic_failure_hint = 'To sign BALL: Use both hands in a curved-5 (claw hand, fingers spread and bent), mirrored. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'ball';
update public.vocabulary_items set generic_failure_hint = 'To sign BIG: Use both hands in a bent ''L'' (L shape with a crooked index), mirrored. Position it in the neutral space in front of your chest and move it along a curved path.' where id = 'big';
update public.vocabulary_items set generic_failure_hint = 'To sign BIRD: Make a ''G'' (index and thumb extended, pointing sideways) with one hand. Hold it at your mouth, tapping in place.' where id = 'bird';
update public.vocabulary_items set generic_failure_hint = 'To sign BODY: Use both hands in an open ''B'' (flat hand, fingers spread a little), mirrored. Position it at your collarbone and move it in a straight line.' where id = 'body';
update public.vocabulary_items set generic_failure_hint = 'To sign BUILDING: Use both hands in a flat ''H'' (index and middle out and flattened), mirrored. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'building';
update public.vocabulary_items set generic_failure_hint = 'To sign CAR: Use both hands in an ''S'' (closed fist, thumb across the front), mirrored. Position it in the neutral space in front of your chest and move it along a curved path, repeating the motion.' where id = 'car';
update public.vocabulary_items set generic_failure_hint = 'To sign CLEAN: Make an open ''B'' (flat hand, fingers spread a little) with your dominant hand over your other hand. Position it in the palm of your other hand and move it along a curved path, repeating the motion.' where id = 'clean';
update public.vocabulary_items set generic_failure_hint = 'To sign CLOTHES: Use both hands in an open ''5'' (all five fingers spread), mirrored. Position it high on your chest and move it along a curved path, repeating the motion.' where id = 'clothes';
update public.vocabulary_items set generic_failure_hint = 'To sign COLD: Use both hands in an ''S'' (closed fist, thumb across the front), mirrored. Position it just out from your body and move it in a straight line, repeating the motion.' where id = 'cold';
update public.vocabulary_items set generic_failure_hint = 'To sign COLOR: Make an open ''5'' (all five fingers spread) with one hand. Hold it at your chin, tapping in place.' where id = 'color';
update public.vocabulary_items set generic_failure_hint = 'To sign COOL: Make an open ''5'' (all five fingers spread) with one hand. Hold it high on your chest, tapping in place.' where id = 'cool';
update public.vocabulary_items set generic_failure_hint = 'To sign DARK: Use both hands in an open ''5'' (all five fingers spread), mirrored. Position it in the neutral space in front of your chest and move it in a straight line.' where id = 'dark';
update public.vocabulary_items set generic_failure_hint = 'To sign DELICIOUS: Make an ''8'' (middle finger touching thumb) with one hand. Position it at your mouth and move it in a straight line.' where id = 'delicious';
update public.vocabulary_items set generic_failure_hint = 'To sign DIFFERENT: Use both hands in a ''1'' (index finger pointing up, others closed), mirrored. Position it in the neutral space in front of your chest and move it in a straight line.' where id = 'different';
update public.vocabulary_items set generic_failure_hint = 'To sign DIRTY: Make an open ''5'' (all five fingers spread) with one hand. Hold it under your chin, tapping in place.' where id = 'dirty';
update public.vocabulary_items set generic_failure_hint = 'To sign DOCTOR: Make a flat-O (fingertips pinched to the thumb) with one hand. Position it on the inside of your wrist and move it in a straight line, repeating the motion.' where id = 'doctor';
update public.vocabulary_items set generic_failure_hint = 'To sign DOG: Make a ''D'' (index up, thumb and middle finger forming a circle) with one hand. Hold it in the neutral space in front of your chest, tapping in place.' where id = 'dog';
update public.vocabulary_items set generic_failure_hint = 'To sign DRINK: Make a ''C'' (hand curved into a C shape) with one hand. Position it just out from your head and move it in a straight line.' where id = 'drink';
update public.vocabulary_items set generic_failure_hint = 'To sign EAT: Make an ''O'' (fingers and thumb form a round O) with one hand. Position it at your mouth and move it in a straight line, repeating the motion.' where id = 'eat';
update public.vocabulary_items set generic_failure_hint = 'To sign ENJOY: Use both hands in an open ''B'' (flat hand, fingers spread a little), mirrored. Position it high on your chest and move it in a circle, repeating the motion.' where id = 'enjoy';
update public.vocabulary_items set generic_failure_hint = 'To sign FAMILY: Use both hands in an ''F'' (index and thumb form a circle, other fingers up), mirrored. Position it in the neutral space in front of your chest and move it along a curved path.' where id = 'family';
update public.vocabulary_items set generic_failure_hint = 'To sign FEEL: Make an open-8 (middle finger bent toward thumb, hand open) with one hand. Position it high on your chest and move it along a curved path, repeating the motion.' where id = 'feel';
update public.vocabulary_items set generic_failure_hint = 'To sign FINISH: Use both hands in an open ''5'' (all five fingers spread), mirrored. Hold it in the neutral space in front of your chest.' where id = 'finish';
update public.vocabulary_items set generic_failure_hint = 'To sign FLOWER: Make a flat-O (fingertips pinched to the thumb) with one hand. Position it by your cheek or nose and move it along a curved path.' where id = 'flower';
update public.vocabulary_items set generic_failure_hint = 'To sign FOLLOW: Use both hands in a ''4'' (four fingers up, thumb tucked), mirrored. Position it in the neutral space in front of your chest and trace a Z-shaped path.' where id = 'follow';
update public.vocabulary_items set generic_failure_hint = 'To sign FRIEND: Use both hands in a curved-1 (slightly hooked index), mirrored. Position it in the neutral space in front of your chest and move it as the reference shows.' where id = 'friend';
update public.vocabulary_items set generic_failure_hint = 'To sign FRUIT: Make an ''F'' (index and thumb form a circle, other fingers up) with one hand. Hold it at your mouth, tapping in place.' where id = 'fruit';
update public.vocabulary_items set generic_failure_hint = 'To sign FUN: Make an ''H'' (index and middle fingers out together) with one hand. Hold it by your cheek or nose.' where id = 'fun';
update public.vocabulary_items set generic_failure_hint = 'To sign GAME: Use both hands in an ''A'' (closed fist, thumb up the side), mirrored. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'game';
update public.vocabulary_items set generic_failure_hint = 'To sign GOOD: Make an open ''B'' (flat hand, fingers spread a little) with one hand. Position it at your chin and move it in a straight line.' where id = 'good';
update public.vocabulary_items set generic_failure_hint = 'To sign HAIR: Make an ''F'' (index and thumb form a circle, other fingers up) with one hand. Position it up at your head and move it in a straight line, repeating the motion.' where id = 'hair';
update public.vocabulary_items set generic_failure_hint = 'To sign HAPPY: Make an open ''B'' (flat hand, fingers spread a little) with one hand. Position it high on your chest and move it along a curved path, repeating the motion.' where id = 'happy';
update public.vocabulary_items set generic_failure_hint = 'To sign HEALTH: Use both hands in a curved-5 (claw hand, fingers spread and bent), mirrored. Position it at your shoulder and move it in a straight line.' where id = 'health';
update public.vocabulary_items set generic_failure_hint = 'To sign HELP: Your dominant hand makes an ''A'' (closed fist, thumb up the side) and your other (still) hand makes a ''B'' handshape. Position it in the palm of your other hand and move it in a straight line, repeating the motion.' where id = 'help';
update public.vocabulary_items set generic_failure_hint = 'To sign HOT: Make a flat spread-5 (flat hand, fingers apart) with one hand. Position it just out from your head and move it along a curved path.' where id = 'hot';
update public.vocabulary_items set generic_failure_hint = 'To sign HOUSE: Use both hands in a flat ''B'' (flat hand, fingers together), mirrored. Position it in the neutral space in front of your chest and move it along a curved path.' where id = 'house';
update public.vocabulary_items set generic_failure_hint = 'To sign HURT: Use both hands in a ''1'' (index finger pointing up, others closed), mirrored. Position it in the neutral space in front of your chest and move it in a circle, repeating the motion.' where id = 'hurt';
update public.vocabulary_items set generic_failure_hint = 'To sign KID: Make a horns hand (index and pinky out) with one hand. Hold it at your upper lip, tapping in place.' where id = 'kid';
update public.vocabulary_items set generic_failure_hint = 'To sign LEARN: Your dominant hand makes a flat spread-5 (flat hand, fingers apart) and your other (still) hand makes a ''B'' handshape. Hold it in the palm of your other hand.' where id = 'learn';
update public.vocabulary_items set generic_failure_hint = 'To sign LOVE: Use both hands in an ''A'' (closed fist, thumb up the side), mirrored. Hold it high on your chest.' where id = 'love';
update public.vocabulary_items set generic_failure_hint = 'To sign MONEY: Your dominant hand makes a flat-O (fingertips pinched to the thumb) and your other (still) hand makes a ''B'' handshape. Position it in the palm of your other hand and move it in a straight line, repeating the motion.' where id = 'money';
update public.vocabulary_items set generic_failure_hint = 'To sign MUSIC: Make an open ''B'' (flat hand, fingers spread a little) with one hand. Position it just out from your arm and move it along a curved path, repeating the motion.' where id = 'music';
update public.vocabulary_items set generic_failure_hint = 'To sign NICE: Make an open ''B'' (flat hand, fingers spread a little) with your dominant hand over your other hand. Position it in the palm of your other hand and move it in a straight line.' where id = 'nice';
update public.vocabulary_items set generic_failure_hint = 'To sign NOTHING: Use both hands in an ''O'' (fingers and thumb form a round O), mirrored. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'nothing';
update public.vocabulary_items set generic_failure_hint = 'To sign NUMBERS: Use both hands in a flat-O (fingertips pinched to the thumb), mirrored. Position it in the neutral space in front of your chest and move it as the reference shows.' where id = 'numbers';
update public.vocabulary_items set generic_failure_hint = 'To sign OLD: Make an ''O'' (fingers and thumb form a round O) with one hand. Position it at your chin and move it in a straight line.' where id = 'old';
update public.vocabulary_items set generic_failure_hint = 'To sign PAPER: Make an open ''5'' (all five fingers spread) with your dominant hand over your other hand. Position it in the palm of your other hand and move it along a curved path, repeating the motion.' where id = 'paper';
update public.vocabulary_items set generic_failure_hint = 'To sign PEOPLE: Use both hands in a ''P'' (K shape pointed downward), mirrored. Position it in the neutral space in front of your chest and move it in a circle, repeating the motion.' where id = 'people';
update public.vocabulary_items set generic_failure_hint = 'To sign PLAY: Use both hands in a ''Y'' (thumb and pinky out, others closed), mirrored. Hold it in the neutral space in front of your chest, tapping in place.' where id = 'play';
update public.vocabulary_items set generic_failure_hint = 'To sign PRETTY: Make an open ''5'' (all five fingers spread) with one hand. Hold it just out from your head.' where id = 'pretty';
update public.vocabulary_items set generic_failure_hint = 'To sign RAIN: Use both hands in a spread open-E (fingers loosely curled and apart), mirrored. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'rain';
update public.vocabulary_items set generic_failure_hint = 'To sign READ: Your dominant hand makes a ''V'' (index and middle fingers up in a V) and your other (still) hand makes a ''B'' handshape. Position it just out from your other hand and move it in a straight line, repeating the motion.' where id = 'read';
update public.vocabulary_items set generic_failure_hint = 'To sign RED: Make a ''1'' (index finger pointing up, others closed) with one hand. Hold it at your mouth, tapping in place.' where id = 'red';
update public.vocabulary_items set generic_failure_hint = 'To sign REMEMBER: Make an ''A'' (closed fist, thumb up the side) with one hand. Hold it at your forehead.' where id = 'remember';
update public.vocabulary_items set generic_failure_hint = 'To sign SAD: Use both hands in an open ''5'' (all five fingers spread), mirrored. Position it just out from your head and move it in a straight line.' where id = 'sad';
update public.vocabulary_items set generic_failure_hint = 'To sign SAFE: Use both hands in an ''S'' (closed fist, thumb across the front), mirrored. Position it in the neutral space in front of your chest and move it along a curved path.' where id = 'safe';
update public.vocabulary_items set generic_failure_hint = 'To sign SAME: Make a ''Y'' (thumb and pinky out, others closed) with one hand. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'same';
update public.vocabulary_items set generic_failure_hint = 'To sign SCARED: Use both hands in an open ''5'' (all five fingers spread), mirrored. Position it just out from your body and move it in a straight line, repeating the motion.' where id = 'scared';
update public.vocabulary_items set generic_failure_hint = 'To sign SCHOOL: Make an open ''5'' (all five fingers spread) with your dominant hand over your other hand. Position it in the palm of your other hand and move it in a straight line, repeating the motion.' where id = 'school';
update public.vocabulary_items set generic_failure_hint = 'To sign SEE: Make a ''P'' (K shape pointed downward) with one hand. Position it near your eye and move it in a straight line.' where id = 'see';
update public.vocabulary_items set generic_failure_hint = 'To sign SICK: Use both hands in an open-8 (middle finger bent toward thumb, hand open), mirrored. Position it at your forehead and move it in a straight line.' where id = 'sick';
update public.vocabulary_items set generic_failure_hint = 'To sign SLEEP: Make an open ''5'' (all five fingers spread) with one hand. Position it just out from your head and move it in a straight line.' where id = 'sleep';
update public.vocabulary_items set generic_failure_hint = 'To sign SNOW: Make a flat spread-5 (flat hand, fingers apart) with one hand. Position it high on your chest and move it in a straight line.' where id = 'snow';
update public.vocabulary_items set generic_failure_hint = 'To sign SPORTS: Use both hands in an ''A'' (closed fist, thumb up the side), mirrored. Hold it in the neutral space in front of your chest, tapping in place.' where id = 'sports';
update public.vocabulary_items set generic_failure_hint = 'To sign SUN: Make a flat-O (fingertips pinched to the thumb) with one hand. Position it just out from your head and move it in a circle.' where id = 'sun';
update public.vocabulary_items set generic_failure_hint = 'To sign SWEET: Make an open ''B'' (flat hand, fingers spread a little) with one hand. Hold it at your chin, tapping in place.' where id = 'sweet';
update public.vocabulary_items set generic_failure_hint = 'To sign SWIM: Use both hands in a flat ''B'' (flat hand, fingers together), mirrored. Position it in the neutral space in front of your chest and move it along a curved path, repeating the motion.' where id = 'swim';
update public.vocabulary_items set generic_failure_hint = 'To sign TIME: Make a bent-1 (crooked index finger) with one hand. Position it on the back of your wrist and move it in a straight line, repeating the motion.' where id = 'time';
update public.vocabulary_items set generic_failure_hint = 'To sign TIRED: Use both hands in a ''C'' (hand curved into a C shape), mirrored. Position it at your collarbone and move it along a curved path.' where id = 'tired';
update public.vocabulary_items set generic_failure_hint = 'To sign TREE: Make an open ''5'' (all five fingers spread) with one hand. Hold it in the neutral space in front of your chest, tapping in place.' where id = 'tree';
update public.vocabulary_items set generic_failure_hint = 'To sign UNDERSTAND: Make a baby-O (a small O made with the index and thumb) with one hand. Hold it just out from your head.' where id = 'understand';
update public.vocabulary_items set generic_failure_hint = 'To sign VEGETABLE: Make a ''V'' (index and middle fingers up in a V) with one hand. Hold it at your mouth.' where id = 'vegetable';
update public.vocabulary_items set generic_failure_hint = 'To sign WAIT: Use both hands in an open ''5'' (all five fingers spread), mirrored. Hold it in the neutral space in front of your chest, tapping in place.' where id = 'wait';
update public.vocabulary_items set generic_failure_hint = 'To sign WARM: Make an ''S'' (closed fist, thumb across the front) with one hand. Position it at your mouth and move it in a straight line.' where id = 'warm';
update public.vocabulary_items set generic_failure_hint = 'To sign WATER: Make a ''W'' (index, middle and ring fingers up) with one hand. Position it at your chin and move it in a straight line, repeating the motion.' where id = 'water';
update public.vocabulary_items set generic_failure_hint = 'To sign WHERE: Make a ''1'' (index finger pointing up, others closed) with one hand. Position it in the neutral space in front of your chest and move it in a straight line, repeating the motion.' where id = 'where';
update public.vocabulary_items set generic_failure_hint = 'To sign WORK: Make an ''S'' (closed fist, thumb across the front) with your dominant hand over your other hand. Position it on the back of your other hand and move it in a straight line, repeating the motion.' where id = 'work';
update public.vocabulary_items set generic_failure_hint = 'To sign WRITE: Your dominant hand makes a baby-O (a small O made with the index and thumb) and your other (still) hand makes a ''B'' handshape. Position it in the palm of your other hand and move it in a straight line, repeating the motion.' where id = 'write';

-- DOWN MIGRATION (manual; reversible):
-- Reverts the 80 hints to NULL. Run only to undo this migration.
/*
update public.vocabulary_items set generic_failure_hint = null where id in (
  'animal', 'baby', 'ball', 'big', 'bird', 'body', 'building', 'car',
  'clean', 'clothes', 'cold', 'color', 'cool', 'dark', 'delicious', 'different',
  'dirty', 'doctor', 'dog', 'drink', 'eat', 'enjoy', 'family', 'feel',
  'finish', 'flower', 'follow', 'friend', 'fruit', 'fun', 'game', 'good',
  'hair', 'happy', 'health', 'help', 'hot', 'house', 'hurt', 'kid',
  'learn', 'love', 'money', 'music', 'nice', 'nothing', 'numbers', 'old',
  'paper', 'people', 'play', 'pretty', 'rain', 'read', 'red', 'remember',
  'sad', 'safe', 'same', 'scared', 'school', 'see', 'sick', 'sleep',
  'snow', 'sports', 'sun', 'sweet', 'swim', 'time', 'tired', 'tree',
  'understand', 'vegetable', 'wait', 'warm', 'water', 'where', 'work', 'write'
);
*/

